services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nest-node
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    environment:
      - NODE_ENV=dev
    command:
      [
        "sh",
        "-c",
        "if [ ! -f node_modules/.package-lock.json ] || ! cmp -s package-lock.json node_modules/.package-lock.json; then npm install --no-audit --no-fund && cp package-lock.json node_modules/.package-lock.json; fi; npm run start:dev"
      ]
    depends_on:
      - mongo

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: angular-node
    ports:
      - "4200:4200"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=dev
    command:
      [
        "sh",
        "-c",
        "if [ ! -f node_modules/.package-lock.json ] || ! cmp -s package-lock.json node_modules/.package-lock.json; then npm install --no-audit --no-fund && cp package-lock.json node_modules/.package-lock.json; fi; npm start"
      ]
    depends_on:
      - api

  mongo:
    image: mongo:8
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  api_node_modules:
  web_node_modules:
